Add support to Python 3.10
unhaggle/django-cronman pull request #38
Opened 2022-06-01 15:29 UTC by gamorales

## Description

The purpose of this PR is to upgrade python 3.6 to 3.10 in django-cronman library.

## Downtime Check

- [x] Downtime check pass

## Testing

### Quality Check stamps

  I tested it and it works:

  - [x] Guillermo Alfonso Morales
  - [x] Jhonatan da Rosa
  - [x] Danial Malik
  - [x] José Maria Dominguez

### How to test this

- Steps to Reproduce
    
    1. docker-compose run --rm django-cronman pytest
    2. Create a cron task in .../uh-adm/cron/crontask/
    
- Expected Results (After change)

- Previous results (Before change)

## Deployment procedure

### Steps for deployment

### Before deployment

  -

### After Deployment

  -

Related tier3 PR https://github.com/unhaggle/tier3/pull/6415

2022-06-07 10:36 UTC, danialmalik requested changes
- Please add a link to the related tier3 PR where it can be tested.

2022-06-07 10:36 UTC, danialmalik commented on cronman/models.py
> +from django.utils import six
It doesn't do us any benefit if we remove `six` from one source and add it from another source.
 lets remove it altogether if possible?

2022-06-07 10:36 UTC, danialmalik commented on cronman/version.py
> +__version__ = "3.0.0"
There is already a published version 3.0.0. I think it wasn't updated here. 
![image](https://user-images.githubusercontent.com/42166091/172359752-eaf86d2c-3152-4bea-8ea5-6801ed3fb1d7.png)


So let's use 4.0.0.

2022-06-07 17:54 UTC, gamorales commented on cronman/version.py
> +__version__ = "3.0.0"
Updated to 4.0.0

2022-06-07 17:54 UTC, gamorales commented on cronman/models.py
> +from django.utils import six
Six library deleted.

2022-06-08 08:57 UTC, danialmalik reviewed
While we're at it, could we please remove other occurrences of `six` as well?

2022-06-14 12:17 UTC, danialmalik approved these changes

2022-06-15 05:41 UTC, rcichy approved these changes

2022-06-16 19:16 UTC, mbarakaja requested changes
What about Travis? The tests must run in Travis with Python version from 3.6 to 3.10.

2022-06-16 19:16 UTC, mbarakaja commented on cronman/version.py
> +__version__ = "4.0.0b38dev0"
Why is there a jump to 4.x here? Does that mean that it isn't backward compatible?

2022-06-17 09:30 UTC, danialmalik commented on cronman/version.py
> +__version__ = "4.0.0b38dev0"
Ah yes. My bad, didn't realize that the purpose was to keep it backward compatible :facepalm: 

@gamorales could you change the version? There is already a version 3.0.0 (being used in t3). So can you update this version to `3.1.0`?

2022-06-21 15:14 UTC, mbarakaja approved these changes

2022-06-22 08:39 UTC, danialmalik commented
@gamorales since the PR is approved and ready to be merged. Could you please change the version from the current "Dev" version to a live one" `3.1.0` ?

2022-06-22 12:50 UTC, gamorales commented
> @gamorales since the PR is approved and ready to be merged. Could you please change the version from the current "Dev" version to a live one" `3.1.0` ?

Done, should I update already tier3 library too?

2022-06-24 11:38 UTC, danialmalik commented
@unhaggle/smooth-operators since you are guardian of this package? could you please merge the PR and release a new version? (and may be review the PR as well?)

Thanks guys!!

2022-06-27 12:13 UTC, jhonatandarosa approved these changes

2022-06-27 12:48 UTC, merged