MI-1505: Adding templates to wrap long text - initial config
unhaggle/django-cronman pull request #40
Opened 2022-09-07 00:39 UTC by ericrommel

Initial development that adds templates to wrap long texts on the views.

2022-09-12 21:04 UTC, JakeBallantyne requested changes
Hey man! Looking good, it works - changes are to clean up the template structure to avoid conflict in the future.

One thing I still don't understand - why are tests skipped with the `setup.py test` command?

2022-09-12 21:04 UTC, JakeBallantyne commented on cronman/tests/test_admin.py
> +        assert response.status_code == 200
```suggestion
        assert response.status_code == 200
        
        loaded_template = response.templates[0]
        assert (
            loaded_template.name == "cronman/admin/cron_task/change_form.html")
```

2022-09-12 21:04 UTC, JakeBallantyne commented on cronman/tests/test_admin.py
> +        assert response.status_code == 200
to ensure the correct template was loaded

2022-09-12 21:04 UTC, JakeBallantyne commented on cronman/admin.py
> +    change_list_template = "admin/cronman/cron/cron_task/change_list.html"
```suggestion
    change_form_template = "cronman/admin/cron_task/change_form.html"
    change_list_template = "cronman/admin/cron_task/change_list.html"
```

2022-09-12 21:04 UTC, JakeBallantyne commented on cronman/admin.py
> +    change_list_template = "admin/cronman/cron/cron_task/change_list.html"
and change in corresponding admin class, and reorder the templates dir. This is required so this app becomes pluggable into a dependant project. In this case, an overlap would be rare, but if the django admin app included its own `cron_task` template dir, we would be in trouble.

2022-09-13 16:15 UTC, ericrommel commented on cronman/tests/test_admin.py
> +        assert response.status_code == 200
Done

2022-09-13 16:15 UTC, ericrommel commented on cronman/admin.py
> +    change_list_template = "admin/cronman/cron/cron_task/change_list.html"
Done

2022-09-20 20:04 UTC, ericrommel commented
> Hey man! Looking good, it works - changes are to clean up the template structure to avoid conflict in the future.
> 
> One thing I still don't understand - why are tests skipped with the `setup.py test` command?

Hey @JakeBallantyne, thank you so much for your help. It is now working. I have cleaned up the code and as we can see, all tests are now passing.

2022-09-20 22:00 UTC, jbal requested changes
One fast change!

2022-09-20 22:00 UTC, jbal commented on cronman/tests/test_admin.py
> +class TestCronTaskAdmin(BaseCronTestCase):
Can we re-comment `ROOT_URLCONF` and apply this on every test we need the url conf for?
```
@override_settings(ROOT_URLCONF=__name__)
class TestView(TestCase):
        ...
```

2022-09-21 15:28 UTC, mbarakaja approved these changes
👍🏽

2022-09-21 19:29 UTC, jbal approved these changes
Great stuff man!

2022-09-22 19:17 UTC, Xyloxy approved these changes
LGTM

2022-09-22 21:37 UTC, merged